version: "3.3"

services: 
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - SQLITE_PATH=/app/dataposition.db
    env_file:
      - .env
    volumes:
      - "./dataposition.db:/app/dataposition.db"
