name: fast-dataposition
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pandas
  - pip:
      - black
      - fastapi[all]
      - flake8
      - isort
      - mypy
      - pycodestyle
      - pydantic[email]
      - pyflakes
