"""Create profiles, users, questions tables

Revision ID: 55c0348515d2
Revises: 35604fa021c1
Create Date: 2022-04-13 09:37:17.370097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c0348515d2'
down_revision = '35604fa021c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
