"""Create profiles, users, questions tables

Revision ID: 64fcd086cfd7
Revises: 55c0348515d2
Create Date: 2022-04-13 09:44:50.879879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fcd086cfd7'
down_revision = '55c0348515d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
