"""Create profiles, users, questions tables

Revision ID: a6d983214b64
Revises: 64fcd086cfd7
Create Date: 2022-04-13 09:49:14.843865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d983214b64'
down_revision = '64fcd086cfd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
